import { BudgetController } from '@ava/llm'
import type { PreparedArtifact, StoredOpportunity } from '@ava/db'
import type { AppContext } from './context'
import { buildProviderRegistry } from './provider-setup'
import { proactivePacket } from './proactive-packet'

/**
 * Preparation (S5-T10, brief §17–18).
 *
 * Preparation is INTERNAL. It writes a draft into AVA's own store and reaches
 * nothing outside: no e-mail, no message, no document edit, no calendar. The
 * user asked for none of this, so the blast radius of being wrong has to be
 * zero.
 *
 * What V0 can prepare is deliberately small: a review checklist assembled
 * deterministically from the change and the dependent objects. It is a draft,
 * not a conclusion, and it is system-origin — so it can never come back as
 * evidence for the opportunity that produced it.
 */
export type PreparationOutcome =
  | { prepared: true; artifact: PreparedArtifact; decisionRecordId: string }
  | { prepared: false; verdict: string; reasons: readonly string[]; decisionRecordId: string }

export async function prepareForOpportunity(
  ctx: AppContext, opportunityId: string, now: Date = new Date(),
): Promise<PreparationOutcome> {
  const opportunity = await ctx.opportunities.findById(opportunityId)
  if (opportunity === null) throw new Error(`no such opportunity: ${opportunityId}`)

  await ctx.telemetry.record({
    eventType: 'preparation_started', occurredAt: now,
    subjectType: 'opportunity', subjectId: opportunityId,
    workstreamId: opportunity.workstreamId,
  })

  // The Prepare Policy verdict was computed at generation time, against the
  // context that existed then. It is read, not recomputed: re-deciding now
  // with today's information is exactly the retroactive edit that would make
  // the record untrustworthy.
  if (opportunity.prepare.verdict !== 'PASS') {
    const drId = await recordPreparationDecision(ctx, opportunity, {
      prepared: false,
      verdict: opportunity.prepare.verdict,
      reasons: opportunity.prepare.reasons,
      mode: 'local_only', costUsd: null, budgetDetail: null,
    })
    await ctx.telemetry.record({
      eventType: 'preparation_denied', occurredAt: now,
      subjectType: 'opportunity', subjectId: opportunityId,
      workstreamId: opportunity.workstreamId, decisionRecordId: drId,
      payload: { verdict: opportunity.prepare.verdict, reasons: opportunity.prepare.reasons },
    })
    return {
      prepared: false, verdict: opportunity.prepare.verdict,
      reasons: opportunity.prepare.reasons, decisionRecordId: drId,
    }
  }

  // A model-assisted draft would be nicer to read. It is asked for explicitly
  // and refused explicitly: with no operational cap configured, the Budget
  // Controller is closed, and ADR-21 requires caps before the first paid call.
  const { caps } = await buildProviderRegistry()
  const budget = new BudgetController(caps)
  const modelDecision = budget.authorize(ESTIMATED_MODEL_COST_USD)

  const body = deterministicChecklist(opportunity)
  const artifact = await ctx.prepared.create({
    opportunityId,
    kind: 'review_checklist',
    title: `Review checklist — ${opportunity.headline}`,
    body,
    // Honest label: this draft was assembled locally from stored structure.
    // Nothing was generated by a model, and nothing claims to have been.
    executionMode: 'local_only',
    modelRunId: null,
    estimatedCostUsd: 0,
    actualCostUsd: 0,
    preparedAt: now,
  })

  const drId = await recordPreparationDecision(ctx, opportunity, {
    prepared: true,
    verdict: 'PASS',
    reasons: opportunity.prepare.reasons,
    mode: 'local_only',
    costUsd: 0,
    // The downgrade is recorded, not silent: a cheaper path taken without a
    // DecisionRecord is indistinguishable from a cheaper path taken by accident.
    budgetDetail: modelDecision.allowed
      ? 'a model-assisted draft was authorised but V0 prepares deterministically'
      : `model-assisted drafting refused: ${modelDecision.reason}; prepared the deterministic checklist instead`,
  })

  await ctx.opportunities.markStatus(opportunityId, 'prepared', now)
  await ctx.telemetry.record({
    eventType: 'preparation_completed', occurredAt: now,
    subjectType: 'prepared_artifact', subjectId: artifact.id,
    workstreamId: opportunity.workstreamId, decisionRecordId: drId,
    payload: { opportunityId, executionMode: 'local_only', costUsd: 0 },
  })

  return { prepared: true, artifact, decisionRecordId: drId }
}

/** What a model-assisted draft would plausibly cost. Used only to ask. */
const ESTIMATED_MODEL_COST_USD = 0.02

/**
 * The checklist. Assembled from what is recorded, phrased so that it never
 * asserts the dependent work is wrong — the relation shows a dependency
 * changed, which is a reason to look, not a finding.
 */
function deterministicChecklist(o: StoredOpportunity): string {
  const lines = [
    `Why this came up: ${o.detail}`,
    '',
    'To check:',
    ...o.affectedObjects.map((a) =>
      `- ${a.objectType} ${a.objectId} (${a.relation.replace(/_/g, ' ')}, via ${a.viaKind ?? 'direct'}) — does it still hold?`),
    '',
    o.minimalAction ? `Suggested next step: ${o.minimalAction}` : 'No next step could be named.',
    '',
    `Evidence behind this: ${o.originEvidenceIds.join(', ')}`,
    `Evidence strength: ${o.strength}. Context at generation: ${o.contextHealth}.`,
    '',
    'AVA prepared this draft without being asked. It is a starting point, not a decision.',
  ]
  return lines.join('\n')
}

interface PreparationDecisionInput {
  prepared: boolean
  verdict: string
  reasons: readonly string[]
  mode: 'mock' | 'external' | 'local_only'
  costUsd: number | null
  budgetDetail: string | null
}

/**
 * The preparation DecisionRecord — DISTINCT from the show record.
 *
 * Two separate records is the point (spec §12): a person auditing this must be
 * able to see that the decision to prepare and the decision to show were taken
 * independently, and neither one justified the other.
 */
async function recordPreparationDecision(
  ctx: AppContext, o: StoredOpportunity, input: PreparationDecisionInput,
): Promise<string> {
  return ctx.decisionRecords.append({
    kind: 'opportunity_preparation',
    workstreamId: o.workstreamId,
    request: `prepare for opportunity ${o.id}`,
    queryKind: 'change',
    retrievalResultIds: o.originEvidenceIds,
    packet: proactivePacket({
      id: o.id, question: `prepare for opportunity ${o.id}`,
      health: o.contextHealth, at: new Date(),
    }),
    excluded: [],
    contextHealthId: null,
    contextHealthState: o.contextHealth,
    provider: null, model: null, promptId: null, promptVersion: null, modelRunId: null,
    executionMode: input.mode,
    groundingValid: true,
    groundingFailures: [],
    answer: input.prepared ? 'prepared a review checklist' : 'did not prepare',
    answerEvidenceIds: o.originEvidenceIds,
    uncertainties: [...input.reasons, ...(input.budgetDetail ? [input.budgetDetail] : [])],
    abstained: !input.prepared,
    abstentionReason: input.prepared ? null : `prepare policy returned ${input.verdict}`,
    fallbackUsed: false,
    errorDetail: null,
    declaredCognitionIds: [],
    hypothesisIds: [],
    knowledgeIds: [],
    cognitiveAuthority: null,
    scopeMatch: {
      opportunityId: o.id,
      policy: 'prepare',
      policyVersion: o.prepare.version,
      verdict: input.verdict,
      costUsd: input.costUsd,
    },
  })
}
