/**
 * Context Health (baseline §16, spec §14.1, plan §18).
 *
 * Deterministic by construction: no dimension consults a model. Health is a
 * statement about what AVA can see, and a model cannot tell you what is
 * missing from its own input.
 *
 * Health is computed PER TASK. There is no global "system health": whether a
 * missing calendar matters depends entirely on the question being asked.
 */
export type ContextHealthState = 'HEALTHY' | 'DEGRADED' | 'INSUFFICIENT'

/** The ten dimensions named by the implementation plan. */
export type HealthDimensionId =
  | 'expected_sources_available'
  | 'source_freshness'
  | 'temporal_coverage'
  | 'ingestion_success'
  | 'entity_resolution_pending'
  | 'artifacts_without_current_version'
  | 'unresolved_contradictions'
  | 'permission_blocked_coverage'
  | 'parsing_failures'
  | 'lineage_completeness'
  | 'declared_cognition_coverage'

export const HEALTH_DIMENSIONS: readonly HealthDimensionId[] = [
  'expected_sources_available',
  'source_freshness',
  'temporal_coverage',
  'ingestion_success',
  'entity_resolution_pending',
  'artifacts_without_current_version',
  'unresolved_contradictions',
  'permission_blocked_coverage',
  'parsing_failures',
  'lineage_completeness',
  // Slice 4: whether AVA holds anything the user actually TOLD her about the
  // context being asked about. Immaterial to work-state questions, decisive
  // for personal ones.
  'declared_cognition_coverage',
] as const

/**
 * `not_applicable` is a real, useful outcome and is NOT the same as `ok`.
 * A dimension that could not be evaluated must not be reported as healthy.
 */
export type DimensionVerdict = 'ok' | 'degraded' | 'insufficient' | 'not_applicable'

export interface HealthDimension {
  id: HealthDimensionId
  verdict: DimensionVerdict
  /** Plain statement of what was observed. Never generated by a model. */
  detail: string
  /** Whether this dimension can decide the aggregate for the task at hand. */
  material: boolean
}

export interface ContextHealthResult {
  state: ContextHealthState
  dimensions: readonly HealthDimension[]
  /** Material gaps, in the order they were evaluated. Shown to the user. */
  gaps: readonly string[]
  /** The dimension that determined the aggregate, when one did. */
  decidedBy: HealthDimensionId | null
}

const RANK: Record<ContextHealthState, number> = {
  HEALTHY: 0,
  DEGRADED: 1,
  INSUFFICIENT: 2,
}

function stateOf(verdict: DimensionVerdict): ContextHealthState | null {
  if (verdict === 'degraded') return 'DEGRADED'
  if (verdict === 'insufficient') return 'INSUFFICIENT'
  return null
}

/**
 * Aggregates dimensions for one task.
 *
 * The aggregate is the WORST material dimension. Immaterial dimensions are
 * still reported — the user can see them — but they cannot pull an answerable
 * question into abstention, and they cannot make an unanswerable one look
 * healthy.
 */
export function aggregateHealth(dimensions: readonly HealthDimension[]): ContextHealthResult {
  let state: ContextHealthState = 'HEALTHY'
  let decidedBy: HealthDimensionId | null = null
  const gaps: string[] = []

  for (const d of dimensions) {
    if (!d.material) continue
    const candidate = stateOf(d.verdict)
    if (candidate === null) continue
    gaps.push(`${d.id}: ${d.detail}`)
    if (RANK[candidate] > RANK[state]) {
      state = candidate
      decidedBy = d.id
    }
  }

  return { state, dimensions, gaps, decidedBy }
}

/**
 * Downstream gates (plan §18, OQ-D5 conservative default).
 *
 * These are the contracts that make health behavioural rather than decorative.
 */
export interface HealthGates {
  /** May AVA state something as fact? */
  mayAssert: boolean
  /** May AVA promote knowledge to a more established status? */
  mayPromote: boolean
  /** May AVA prepare work that depends on a possibly-absent source? */
  mayPrepare: boolean
  /** Must AVA show the gaps alongside the answer? */
  mustShowGaps: boolean
  /** Must AVA abstain outright? */
  mustAbstain: boolean
}

export function gatesFor(state: ContextHealthState): HealthGates {
  switch (state) {
    case 'HEALTHY':
      return { mayAssert: true, mayPromote: true, mayPrepare: true, mustShowGaps: false, mustAbstain: false }
    case 'DEGRADED':
      // An answer is still possible, but it is not allowed to be confident,
      // to promote knowledge, or to drive preparation from an absent source.
      return { mayAssert: true, mayPromote: false, mayPrepare: false, mustShowGaps: true, mustAbstain: false }
    case 'INSUFFICIENT':
      return { mayAssert: false, mayPromote: false, mayPrepare: false, mustShowGaps: true, mustAbstain: true }
  }
}
